# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'historique.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1112, 739)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Ressource/Images/ASRH_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("QWidget#Form{\n"
"    background-color: rgb(240, 242, 245);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Entete = QtWidgets.QFrame(Form)
        self.Entete.setMinimumSize(QtCore.QSize(0, 50))
        self.Entete.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Entete.setStyleSheet("QFrame#Entete{\n"
"    border-radius:4px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    color:#fff;\n"
"    border-radius:7px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(96, 166, 252, 255), stop:1 rgba(105, 131, 243, 255));\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(104, 176, 255, 255), stop:1 rgba(115, 141, 253, 255));\n"
"}")
        self.Entete.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Entete.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Entete.setObjectName("Entete")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Entete)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.HistoriqueEmbaucheBtn = QtWidgets.QPushButton(self.Entete)
        self.HistoriqueEmbaucheBtn.setMinimumSize(QtCore.QSize(141, 33))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.HistoriqueEmbaucheBtn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/BlancIcone/Images/BlancIcon/check-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HistoriqueEmbaucheBtn.setIcon(icon1)
        self.HistoriqueEmbaucheBtn.setObjectName("HistoriqueEmbaucheBtn")
        self.horizontalLayout.addWidget(self.HistoriqueEmbaucheBtn)
        self.HistoriqueOuvriersBtn = QtWidgets.QPushButton(self.Entete)
        self.HistoriqueOuvriersBtn.setMinimumSize(QtCore.QSize(141, 33))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.HistoriqueOuvriersBtn.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/BlancIcone/Images/BlancIcon/circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HistoriqueOuvriersBtn.setIcon(icon2)
        self.HistoriqueOuvriersBtn.setObjectName("HistoriqueOuvriersBtn")
        self.horizontalLayout.addWidget(self.HistoriqueOuvriersBtn)
        self.PersonnaliseBtn = QtWidgets.QPushButton(self.Entete)
        self.PersonnaliseBtn.setMinimumSize(QtCore.QSize(141, 33))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.PersonnaliseBtn.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/BlancIcone/Images/BlancIcon/tool.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PersonnaliseBtn.setIcon(icon3)
        self.PersonnaliseBtn.setObjectName("PersonnaliseBtn")
        self.horizontalLayout.addWidget(self.PersonnaliseBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.Entete)
        self.FrameHistorique = QtWidgets.QFrame(Form)
        self.FrameHistorique.setStyleSheet("QWidget#PaginationPage1{\n"
"border-radius:4px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QHeaderView,QHeaderView::section {\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0, x2:0.522, y2:1, stop:0 rgba(96, 166, 252, 255), stop:1 rgba(105, 131, 243, 255));\n"
"    height:30px;\n"
"    color: \"#eee\";\n"
"    font-weight:bold;\n"
"    font-size: 15px;\n"
"    padding: 4px;\n"
"    border:none;\n"
"}\n"
"\n"
"QTreeWidget#TableauHistorique{\n"
"border:none;\n"
"}\n"
"\n"
"\n"
"QTreeWidget#TableauHistorique:item{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0, x2:0.522, y2:1, stop:0 rgba(96, 166, 252, 0.2), stop:1 rgba(105, 131, 243, 0.2));\n"
"}\n"
"QTreeWidget#TableauHistorique:item:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0, x2:0.522, y2:1, stop:0 rgba(96, 166, 252, 0.3), stop:1 rgba(105, 131, 243, 0.3));\n"
"}\n"
"QTreeWidget#TableauHistorique:item:selected{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0, x2:0.522, y2:1, stop:0 rgba(96, 166, 252, 0.6), stop:1 rgba(105, 131, 243, 0.6));\n"
"}\n"
"")
        self.FrameHistorique.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameHistorique.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameHistorique.setObjectName("FrameHistorique")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.FrameHistorique)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TableauHistorique = QtWidgets.QTreeWidget(self.FrameHistorique)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TableauHistorique.setFont(font)
        self.TableauHistorique.setObjectName("TableauHistorique")
        item_0 = QtWidgets.QTreeWidgetItem(self.TableauHistorique)
        self.verticalLayout_2.addWidget(self.TableauHistorique)
        self.verticalLayout.addWidget(self.FrameHistorique)
        self.Footer = QtWidgets.QFrame(Form)
        self.Footer.setMinimumSize(QtCore.QSize(0, 50))
        self.Footer.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Footer.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    color:#fff;\n"
"    border-radius:7px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(96, 166, 252, 255), stop:1 rgba(105, 131, 243, 255));\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(104, 176, 255, 255), stop:1 rgba(115, 141, 253, 255));\n"
"}")
        self.Footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Footer.setObjectName("Footer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Footer)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ImprimerBtn = QtWidgets.QPushButton(self.Footer)
        self.ImprimerBtn.setMinimumSize(QtCore.QSize(141, 33))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.ImprimerBtn.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/BlancIcone/Images/BlancIcon/printer.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ImprimerBtn.setIcon(icon4)
        self.ImprimerBtn.setObjectName("ImprimerBtn")
        self.horizontalLayout_2.addWidget(self.ImprimerBtn)
        self.GenererPointageBtn = QtWidgets.QPushButton(self.Footer)
        self.GenererPointageBtn.setMinimumSize(QtCore.QSize(141, 33))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.GenererPointageBtn.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/BlancIcone/Images/BlancIcon/trending-up.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.GenererPointageBtn.setIcon(icon5)
        self.GenererPointageBtn.setObjectName("GenererPointageBtn")
        self.horizontalLayout_2.addWidget(self.GenererPointageBtn)
        self.GenererPointageEtImprimerBtn = QtWidgets.QPushButton(self.Footer)
        self.GenererPointageEtImprimerBtn.setMinimumSize(QtCore.QSize(210, 33))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.GenererPointageEtImprimerBtn.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/BlancIcone/Images/BlancIcon/layers.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.GenererPointageEtImprimerBtn.setIcon(icon6)
        self.GenererPointageEtImprimerBtn.setObjectName("GenererPointageEtImprimerBtn")
        self.horizontalLayout_2.addWidget(self.GenererPointageEtImprimerBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.Footer)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Historique pointage"))
        self.HistoriqueEmbaucheBtn.setText(_translate("Form", "Embauches"))
        self.HistoriqueOuvriersBtn.setText(_translate("Form", "Ouvriers"))
        self.PersonnaliseBtn.setText(_translate("Form", "Personnaliser"))
        self.TableauHistorique.headerItem().setText(0, _translate("Form", "Matricule"))
        self.TableauHistorique.headerItem().setText(1, _translate("Form", "Nom"))
        self.TableauHistorique.headerItem().setText(2, _translate("Form", "Heure Arrivee"))
        self.TableauHistorique.headerItem().setText(3, _translate("Form", "Heure Depart"))
        self.TableauHistorique.headerItem().setText(4, _translate("Form", "Date"))
        __sortingEnabled = self.TableauHistorique.isSortingEnabled()
        self.TableauHistorique.setSortingEnabled(False)
        self.TableauHistorique.topLevelItem(0).setText(0, _translate("Form", "0"))
        self.TableauHistorique.topLevelItem(0).setText(1, _translate("Form", "test"))
        self.TableauHistorique.topLevelItem(0).setText(2, _translate("Form", "reteste"))
        self.TableauHistorique.topLevelItem(0).setText(3, _translate("Form", "log"))
        self.TableauHistorique.topLevelItem(0).setText(4, _translate("Form", "Congif"))
        self.TableauHistorique.setSortingEnabled(__sortingEnabled)
        self.ImprimerBtn.setText(_translate("Form", "Imprimer"))
        self.GenererPointageBtn.setText(_translate("Form", "Générer le pointage"))
        self.GenererPointageEtImprimerBtn.setText(_translate("Form", "Générer le pointage et imprimer"))
import img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
