# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 320)
        MainWindow.setMinimumSize(QtCore.QSize(800, 320))
        MainWindow.setMaximumSize(QtCore.QSize(800, 655))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("centralwidget{\n"
"background-color: rgb(255, 0, 0);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1051, 661))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("QWidget#page{\n"
"    background-image: url(:/Ressource/Images/bg.png);\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(51, 95, 159, 255), stop:1 rgba(56, 100, 164, 255));\n"
"}\n"
"\n"
"")
        self.page.setObjectName("page")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setGeometry(QtCore.QRect(410, 10, 370, 301))
        self.frame.setMaximumSize(QtCore.QSize(370, 16777215))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(230, 230, 230, 0.007), stop:1 rgba(239, 239, 239, 0.007));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.labelValeurMatricule = QtWidgets.QLabel(self.frame)
        self.labelValeurMatricule.setGeometry(QtCore.QRect(180, 40, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Script")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.labelValeurMatricule.setFont(font)
        self.labelValeurMatricule.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelValeurMatricule.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelValeurMatricule.setObjectName("labelValeurMatricule")
        self.labelValeurMetric = QtWidgets.QLabel(self.frame)
        self.labelValeurMetric.setGeometry(QtCore.QRect(110, 90, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Script")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.labelValeurMetric.setFont(font)
        self.labelValeurMetric.setStyleSheet("color: rgb(51, 209, 137);")
        self.labelValeurMetric.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelValeurMetric.setObjectName("labelValeurMetric")
        self.labelNom = QtWidgets.QLabel(self.frame)
        self.labelNom.setGeometry(QtCore.QRect(150, 0, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Origin Tech Demo")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.labelNom.setFont(font)
        self.labelNom.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelNom.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelNom.setObjectName("labelNom")
        self.labelHello = QtWidgets.QLabel(self.frame)
        self.labelHello.setGeometry(QtCore.QRect(10, 0, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Origin Tech Demo")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.labelHello.setFont(font)
        self.labelHello.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelHello.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelHello.setObjectName("labelHello")
        self.labelMatricule = QtWidgets.QLabel(self.frame)
        self.labelMatricule.setGeometry(QtCore.QRect(10, 40, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Dissolve light")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.labelMatricule.setFont(font)
        self.labelMatricule.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelMatricule.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelMatricule.setObjectName("labelMatricule")
        self.labelMetric = QtWidgets.QLabel(self.frame)
        self.labelMetric.setGeometry(QtCore.QRect(10, 90, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Dissolve light")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.labelMetric.setFont(font)
        self.labelMetric.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelMetric.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelMetric.setObjectName("labelMetric")
        self.labelStart = QtWidgets.QLabel(self.frame)
        self.labelStart.setGeometry(QtCore.QRect(10, 130, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Glitch Inside")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.labelStart.setFont(font)
        self.labelStart.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelStart.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelStart.setObjectName("labelStart")
        self.labelValeurTemps = QtWidgets.QLabel(self.frame)
        self.labelValeurTemps.setGeometry(QtCore.QRect(110, 130, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Glitch Inside")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.labelValeurTemps.setFont(font)
        self.labelValeurTemps.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelValeurTemps.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelValeurTemps.setObjectName("labelValeurTemps")
        self.OkBtn = QtWidgets.QPushButton(self.frame)
        self.OkBtn.setGeometry(QtCore.QRect(10, 260, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Modern")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.OkBtn.setFont(font)
        self.OkBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.OkBtn.setStyleSheet("border:1px solid;\n"
"border-color: rgba(28, 159, 14,0.6);\n"
"background-color: rgba(28, 159, 14,0.206);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:4px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Ressource/Images/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OkBtn.setIcon(icon)
        self.OkBtn.setIconSize(QtCore.QSize(18, 18))
        self.OkBtn.setObjectName("OkBtn")
        self.CaptureLabel = QtWidgets.QLabel(self.page)
        self.CaptureLabel.setGeometry(QtCore.QRect(10, 10, 380, 300))
        self.CaptureLabel.setMinimumSize(QtCore.QSize(380, 300))
        self.CaptureLabel.setMaximumSize(QtCore.QSize(360, 300))
        self.CaptureLabel.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(230, 230, 230, 0.007), stop:1 rgba(239, 239, 239, 0.007));\n"
"border:2px solid;\n"
"border-color: rgb(49, 93, 154);\n"
"border-radius:2px;")
        self.CaptureLabel.setText("")
        self.CaptureLabel.setObjectName("CaptureLabel")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.OkBtn.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelValeurMatricule.setText(_translate("MainWindow", "00000"))
        self.labelValeurMetric.setText(_translate("MainWindow", "0.0"))
        self.labelNom.setText(_translate("MainWindow", "XXXXXXXXX"))
        self.labelHello.setText(_translate("MainWindow", "XXXXXXXXXXX"))
        self.labelMatricule.setText(_translate("MainWindow", "XXXXXXXXXXXXXXXX"))
        self.labelMetric.setText(_translate("MainWindow", "xxxxxxxxxxxxx"))
        self.labelStart.setText(_translate("MainWindow", "xxxxxxx"))
        self.labelValeurTemps.setText(_translate("MainWindow", "00:00"))
        self.OkBtn.setText(_translate("MainWindow", "dgdgdg"))
import img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
