# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pointage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1111, 736)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Ressource/Images/ASRH_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.StackedWidgetHistorique = QtWidgets.QStackedWidget(Form)
        self.StackedWidgetHistorique.setStyleSheet("QWidget#PaginationPage1{\n"
"border-radius:4px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QHeaderView,QHeaderView::section {\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0, x2:0.522, y2:1, stop:0 rgba(96, 166, 252, 255), stop:1 rgba(105, 131, 243, 255));\n"
"    height:30px;\n"
"    color: \"#eee\";\n"
"    font-weight:bold;\n"
"    font-size: 15px;\n"
"    padding: 4px;\n"
"    border:none;\n"
"}\n"
"\n"
"QTreeWidget#TableauPointageE,QTreeWidget#TableauPointageO{\n"
"border:none;\n"
"}\n"
"\n"
"\n"
"QTreeWidget#TableauHistorique:item{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0, x2:0.522, y2:1, stop:0 rgba(96, 166, 252, 0.2), stop:1 rgba(105, 131, 243, 0.2));\n"
"}\n"
"QTreeWidget#TableauHistorique:item:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0, x2:0.522, y2:1, stop:0 rgba(96, 166, 252, 0.3), stop:1 rgba(105, 131, 243, 0.3));\n"
"}\n"
"QTreeWidget#TableauHistorique:item:selected{\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0, x2:0.522, y2:1, stop:0 rgba(96, 166, 252, 0.6), stop:1 rgba(105, 131, 243, 0.6));\n"
"}\n"
"")
        self.StackedWidgetHistorique.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.StackedWidgetHistorique.setFrameShadow(QtWidgets.QFrame.Raised)
        self.StackedWidgetHistorique.setObjectName("StackedWidgetHistorique")
        self.StackedWidgetHistoriquePage1 = QtWidgets.QWidget()
        self.StackedWidgetHistoriquePage1.setObjectName("StackedWidgetHistoriquePage1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.StackedWidgetHistoriquePage1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TableauPointageE = QtWidgets.QTreeWidget(self.StackedWidgetHistoriquePage1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TableauPointageE.setFont(font)
        self.TableauPointageE.setObjectName("TableauPointageE")
        self.verticalLayout_2.addWidget(self.TableauPointageE)
        self.StackedWidgetHistorique.addWidget(self.StackedWidgetHistoriquePage1)
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("QWidget#TableauPointageO{\n"
"    border:none;\n"
"}")
        self.page.setObjectName("page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.TableauPointageO = QtWidgets.QTreeWidget(self.page)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TableauPointageO.setFont(font)
        self.TableauPointageO.setObjectName("TableauPointageO")
        self.verticalLayout_3.addWidget(self.TableauPointageO)
        self.StackedWidgetHistorique.addWidget(self.page)
        self.verticalLayout.addWidget(self.StackedWidgetHistorique)
        self.Footer = QtWidgets.QFrame(Form)
        self.Footer.setMinimumSize(QtCore.QSize(0, 50))
        self.Footer.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Footer.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    color:#fff;\n"
"    border-radius:7px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(96, 166, 252, 255), stop:1 rgba(105, 131, 243, 255));\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(104, 176, 255, 255), stop:1 rgba(115, 141, 253, 255));\n"
"}")
        self.Footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Footer.setObjectName("Footer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Footer)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ImprimerBtn = QtWidgets.QPushButton(self.Footer)
        self.ImprimerBtn.setMinimumSize(QtCore.QSize(141, 33))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.ImprimerBtn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/BlancIcone/Images/BlancIcon/printer.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ImprimerBtn.setIcon(icon1)
        self.ImprimerBtn.setObjectName("ImprimerBtn")
        self.horizontalLayout_2.addWidget(self.ImprimerBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.Footer)

        self.retranslateUi(Form)
        self.StackedWidgetHistorique.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "POINTAGE"))
        self.TableauPointageE.headerItem().setText(0, _translate("Form", "Matricule"))
        self.TableauPointageE.headerItem().setText(1, _translate("Form", "Nom"))
        self.TableauPointageE.headerItem().setText(2, _translate("Form", "Prénom(s)"))
        self.TableauPointageE.headerItem().setText(3, _translate("Form", "Poste"))
        self.TableauPointageE.headerItem().setText(4, _translate("Form", "Temps d\'activité(En jour)"))
        self.TableauPointageE.headerItem().setText(5, _translate("Form", "Période"))
        self.TableauPointageO.headerItem().setText(0, _translate("Form", "Matricule"))
        self.TableauPointageO.headerItem().setText(1, _translate("Form", "Nom"))
        self.TableauPointageO.headerItem().setText(2, _translate("Form", "Prénom(s)"))
        self.TableauPointageO.headerItem().setText(3, _translate("Form", "Poste"))
        self.TableauPointageO.headerItem().setText(4, _translate("Form", "Temps d\'activité(En heure)"))
        self.TableauPointageO.headerItem().setText(5, _translate("Form", "Période"))
        self.ImprimerBtn.setText(_translate("Form", "Imprimer"))
import img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
